In [1]:
#import dependencies
import pandas as pd
import numpy as np

In [2]:
#open csv file
file_to_load = "sales_data_for_assessment_test.csv"
sales_df=pd.read_csv(file_to_load, sep="\t", engine="python", index_col=0)
sales_df

,skus_count,customer_id,order_id,order_item_id,new_or_repeat_by_order,order_date,sales,product_category,item_sku
0,1.0,29649cb70abee66eb557475c57bbcfee,ebe0ac703444de921b6fb5367260ad26,f4999efe0551c5673c9ccf960e648372,New,2020-04-24 03:04:56,376.913629,noissue Tissue,custom tissue-1000#2colour-50 x 75cm
1,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,8d9ca488c0d0075c8ba3d323cc4842b7,Repeat,2020-08-09 07:43:44,199.020039,noissue Stickers,custom sticker-circle-75 x 75mm-1000
2,1.0,69054b3dade80ebd345ca0de53a796fd,2356a902a3f8d5e5f2b2c2a8ea8b9a34,0fdcfca5e4be5dd653fcfdfa4788c911,New,2020-06-09 15:28:48,123.189307,Compostable Mailers,noissue-mailer-100-370mm-480mm
3,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,04577b5d415b3e8917b3940bd7f1abc4,Repeat,2020-08-09 07:43:44,55.388231,noissue Stamps,custom stamp-manual-8cm x 8cm-1
4,1.0,d0594296cb410dd48e081c620b358451,451a0567ae7c693fb2882b37860ef20d,6a9c15755566cb2f407829fb3637de52,New,2020-06-11 19:51:18,106.625325,Compostable Mailers,noissue-mailer-100-300mm-420mm
...,...,...,...,...,...,...,...,...,...
27732,2.0,167a163973c0dc784268ce1439f44731,12a8f653a63f74268a3c91602e18a931,56defccc63de74d71ae919ab1ecae656,New,2020-08-28 16:08:39,170.119235,noissue Stickers,custom sticker-circle-40 x 40mm-1000
27733,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,8855952988a815c33d84408ee4c60adb,Repeat,2020-05-08 09:46:57,159.147661,noissue Stickers,custom sticker-circle-50 x 50mm-1000
27734,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,848f2cb9ef28ad9b821e91599a3df37a,Repeat,2020-05-08 09:46:57,340.266201,noissue Tissue,own template tissue-1000#2colour-50 x 75cm
27735,NaN,657989c9751e4f61cbf730c67ae15d4e,84409ab5d58daa0e971150510b1c106a,aaaac45627dddcb26224f41f59da5b68,New,2020-05-10 21:44:36,14.546653,Sample,SAMPLEPACK
27736,1.0,0c620bcfc2a979fe9f22acbe0019f276,23e63ace5ccf4dd62ad7da8aab98af93,f8ca2fa0793a913cc0abb9ac6e6b53a5,Repeat,2020-05-19 13:04:48,516.875366,noissue Tissue,own template tissue-2000#1colour-50 x 75cm

In [3]:
#check dtypes 
sales_df.dtypes

skus_count                float64
customer_id                object
order_id                   object
order_item_id              object
new_or_repeat_by_order     object
order_date                 object
sales                     float64
product_category           object
item_sku                   object
dtype: object

In [4]:
#check for duplicated entries
sales_df.duplicated().sum()

0

In [5]:
sales_df.nunique()

skus_count                   10
customer_id               16801
order_id                  20154
order_item_id             27326
new_or_repeat_by_order        2
order_date                20006
sales                     27737
product_category             12
item_sku                    274
dtype: int64

In [6]:
#investigate order_date - why not as datetime format?
print(sales_df["order_date"].min())
sales_df["order_date"].max()

2020-04-01 00:00:00

'2020-09-30 23:55:59'

In [7]:
#convert order_date to datetime format
sales_df["order_date"]=pd.to_datetime(sales_df["order_date"], yearfirst=True)
sales_df.dtypes

skus_count                       float64
customer_id                       object
order_id                          object
order_item_id                     object
new_or_repeat_by_order            object
order_date                datetime64[ns]
sales                            float64
product_category                  object
item_sku                          object
dtype: object

In [8]:
#How many NANs are in the dataset
sales_df.isnull().sum().sum()

2073

In [9]:
#Find the nans - Are they in multiple columns
sku_nans=sales_df["skus_count"].isnull().values.sum()
# sales_df["customer_id"].isnull().values.sum()
# sales_df["order_id"].isnull().values.sum()
order_item_id_nans = sales_df["order_item_id"].isnull().values.sum()
# sales_df["new_or_repeat"].isnull().values.sum()
print(f"Incomplete SKU count: {sku_nans}.")
print(f"Missing Order items ID: {order_item_id_nans}.")
print(f"Total NANs = {sku_nans + order_item_id_nans}.")

Incomplete SKU count: 1833.
Missing Order items ID: 240.
Total NANs = 2073.

In [10]:
#Check for patterns - All the nans are the same product_category and item_sku
sku_df=sales_df.loc[sales_df["skus_count"].isnull()]
print(sku_df.nunique())
sku_df

skus_count                   0
customer_id               1749
order_id                  1771
order_item_id             1771
new_or_repeat_by_order       2
order_date                1771
sales                     1833
product_category             1
item_sku                     1
dtype: int64

,skus_count,customer_id,order_id,order_item_id,new_or_repeat_by_order,order_date,sales,product_category,item_sku
14,NaN,27aab011d9ac195d218b51dbc87e0d4c,76ef8e446748c1fd97219872bebd1e59,b7ae0465809174b88d46e6a9d2493003,New,2020-06-23 15:46:18,94.172438,Sample,SAMPLEPACK
19,NaN,f80c2340ce3b36028b1545f2309dd839,d5a8346d1430dcc6c250b4d17d763423,2d717efa9ad0734fdb6828be1ec2a827,New,2020-09-04 06:45:59,7.261974,Sample,SAMPLEPACK
39,NaN,1458b9161ecc1b1beca494f2173c2494,1a2dc19350343b89927f11b3112982f5,2667d593b8e1728dcfe5fb0b46aa0961,New,2020-08-12 05:04:55,67.878592,Sample,SAMPLEPACK
58,NaN,6fd4972251dbb0c93d4908a57a7edbc0,77c46590cdd3b949f2d8fc954db3f7bf,494833252e1d62803461cf253cb87ea0,New,2020-07-24 14:14:17,38.154387,Sample,SAMPLEPACK
69,NaN,bdbb6845e43f698cb0454e3a7495eaed,c91ff08731de451f1d684816c6bcdbb9,0833894204672ef0a1638151f88415c2,New,2020-06-23 20:06:39,98.496538,Sample,SAMPLEPACK
...,...,...,...,...,...,...,...,...,...
27675,NaN,fe5b5e1f5bdaac754a30a26c1c4dd5f8,336258164b544f8b215c8519b154ec89,0a116604522d6dbebeea354213410971,New,2020-09-23 12:33:51,80.620553,Sample,SAMPLEPACK
27713,NaN,fd6522107f6ee7340d673d02770facf6,c7f6aff9ea71711f53b967ca7fce469a,599144a2f292942bc4b7915f38c3be66,New,2020-07-31 18:51:45,92.181502,Sample,SAMPLEPACK
27728,NaN,72079e9b56f8ca4cf031b22a7bbe864f,321251cd41391f913f95819093b1aa1a,a87469e7e9cfa1c9c744f317a593db06,New,2020-05-01 13:35:43,37.309358,Sample,SAMPLEPACK
27730,NaN,181fac1c8bfb1ff34666c016dc829a46,692b8b03f7f5949a592e48e125235bec,759c7ead28185a57eab2277986e547fb,New,2020-09-15 09:36:39,48.637901,Sample,SAMPLEPACK
27735,NaN,657989c9751e4f61cbf730c67ae15d4e,84409ab5d58daa0e971150510b1c106a,aaaac45627dddcb26224f41f59da5b68,New,2020-05-10 21:44:36,14.546653,Sample,SAMPLEPACK

In [11]:
# # Making the Assumption that a samplepack counts as 1 item
# sales_df["skus_count"].fillna(1.0, inplace=True)
# sales_df

In [12]:
sales_df["skus_count"].isnull().values.sum()

1833

In [13]:
#Check for patterns - All the nans are the same product_category and item_sku, will leave as NAN
orderitemsid_df=sales_df.loc[sales_df["order_item_id"].isnull()]
print(orderitemsid_df.nunique())
orderitemsid_df

skus_count                  1
customer_id               156
order_id                  240
order_item_id               0
new_or_repeat_by_order      2
order_date                111
sales                     240
product_category            1
item_sku                    1
dtype: int64

,skus_count,customer_id,order_id,order_item_id,new_or_repeat_by_order,order_date,sales,product_category,item_sku
14524,1.0,acc9a48b66e96dc521c6c960be44c027,41e995b99855349db14fc6fc469ae65d,NaN,New,2020-05-08,166.513912,PLUS,PLUS
14525,1.0,8169c230c4644610ebc9c28ff4cca428,0ed476c0a030bb4ceedb5e04403b403e,NaN,New,2020-04-02,1154.963655,PLUS,PLUS
14526,1.0,b252426c329a0e47b5f949098cf4ecb3,a7affb3aa3ac024e1e13114c25da11a2,NaN,Repeat,2020-04-05,1846.659838,PLUS,PLUS
14527,1.0,b2ff8cf47b470febf2cad89614c3dc07,0547d5f8c8fd43fe3943c6a03c259e71,NaN,Repeat,2020-04-07,616.139208,PLUS,PLUS
14528,1.0,60a7039de1f1a4186070384c91d80386,7eb8fca3c1cc0551e174bc0828cc83ac,NaN,Repeat,2020-05-12,44387.471712,PLUS,PLUS
...,...,...,...,...,...,...,...,...,...
20809,1.0,3f300a4f1bfb4f469c89c892c6a83a90,8fd8d41a5bff3545ac681f345930e885,NaN,New,2020-09-23,5678.729721,PLUS,PLUS
20810,1.0,0bf86aaa7d4d26b9944a86f475efb8d7,72f876a95360c1e802adf5e2dda680f7,NaN,Repeat,2020-09-27,5146.671816,PLUS,PLUS
20811,1.0,faa72885be38352d5db5640d5299f1a2,6cc750e38e270782fbe8b36efe4644b7,NaN,New,2020-09-28,1188.470720,PLUS,PLUS
20812,1.0,58d2cce8fcf7e37d70fb96259f2d55e5,5827f379a1352dd968189045a60fc00f,NaN,New,2020-09-29,2155.810345,PLUS,PLUS
20813,1.0,0bf86aaa7d4d26b9944a86f475efb8d7,9176bbd1c13a0b275124957737d71f4f,NaN,Repeat,2020-09-29,2482.387667,PLUS,PLUS

In [14]:
#for tableau ease, create 2 separate columns for new/repeat customers (only because binary)
sales_df_dummies=pd.get_dummies(data=sales_df, columns=["new_or_repeat_by_order"], prefix="cust_type")
sales_df_dummies

,skus_count,customer_id,order_id,order_item_id,order_date,sales,product_category,item_sku,cust_type_New,cust_type_Repeat
0,1.0,29649cb70abee66eb557475c57bbcfee,ebe0ac703444de921b6fb5367260ad26,f4999efe0551c5673c9ccf960e648372,2020-04-24 03:04:56,376.913629,noissue Tissue,custom tissue-1000#2colour-50 x 75cm,1,0
1,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,8d9ca488c0d0075c8ba3d323cc4842b7,2020-08-09 07:43:44,199.020039,noissue Stickers,custom sticker-circle-75 x 75mm-1000,0,1
2,1.0,69054b3dade80ebd345ca0de53a796fd,2356a902a3f8d5e5f2b2c2a8ea8b9a34,0fdcfca5e4be5dd653fcfdfa4788c911,2020-06-09 15:28:48,123.189307,Compostable Mailers,noissue-mailer-100-370mm-480mm,1,0
3,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,04577b5d415b3e8917b3940bd7f1abc4,2020-08-09 07:43:44,55.388231,noissue Stamps,custom stamp-manual-8cm x 8cm-1,0,1
4,1.0,d0594296cb410dd48e081c620b358451,451a0567ae7c693fb2882b37860ef20d,6a9c15755566cb2f407829fb3637de52,2020-06-11 19:51:18,106.625325,Compostable Mailers,noissue-mailer-100-300mm-420mm,1,0
...,...,...,...,...,...,...,...,...,...,...
27732,2.0,167a163973c0dc784268ce1439f44731,12a8f653a63f74268a3c91602e18a931,56defccc63de74d71ae919ab1ecae656,2020-08-28 16:08:39,170.119235,noissue Stickers,custom sticker-circle-40 x 40mm-1000,1,0
27733,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,8855952988a815c33d84408ee4c60adb,2020-05-08 09:46:57,159.147661,noissue Stickers,custom sticker-circle-50 x 50mm-1000,0,1
27734,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,848f2cb9ef28ad9b821e91599a3df37a,2020-05-08 09:46:57,340.266201,noissue Tissue,own template tissue-1000#2colour-50 x 75cm,0,1
27735,NaN,657989c9751e4f61cbf730c67ae15d4e,84409ab5d58daa0e971150510b1c106a,aaaac45627dddcb26224f41f59da5b68,2020-05-10 21:44:36,14.546653,Sample,SAMPLEPACK,1,0
27736,1.0,0c620bcfc2a979fe9f22acbe0019f276,23e63ace5ccf4dd62ad7da8aab98af93,f8ca2fa0793a913cc0abb9ac6e6b53a5,2020-05-19 13:04:48,516.875366,noissue Tissue,own template tissue-2000#1colour-50 x 75cm,0,1

In [15]:
sales_df_dummies["new_or_repeat_by_order"] = sales_df["new_or_repeat_by_order"]
sales_df_dummies

,skus_count,customer_id,order_id,order_item_id,order_date,sales,product_category,item_sku,cust_type_New,cust_type_Repeat,new_or_repeat_by_order
0,1.0,29649cb70abee66eb557475c57bbcfee,ebe0ac703444de921b6fb5367260ad26,f4999efe0551c5673c9ccf960e648372,2020-04-24 03:04:56,376.913629,noissue Tissue,custom tissue-1000#2colour-50 x 75cm,1,0,New
1,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,8d9ca488c0d0075c8ba3d323cc4842b7,2020-08-09 07:43:44,199.020039,noissue Stickers,custom sticker-circle-75 x 75mm-1000,0,1,Repeat
2,1.0,69054b3dade80ebd345ca0de53a796fd,2356a902a3f8d5e5f2b2c2a8ea8b9a34,0fdcfca5e4be5dd653fcfdfa4788c911,2020-06-09 15:28:48,123.189307,Compostable Mailers,noissue-mailer-100-370mm-480mm,1,0,New
3,2.0,b5ad5ba050d28afdc5da20475216f4ab,662539ec2021c4b79518b257ac839e00,04577b5d415b3e8917b3940bd7f1abc4,2020-08-09 07:43:44,55.388231,noissue Stamps,custom stamp-manual-8cm x 8cm-1,0,1,Repeat
4,1.0,d0594296cb410dd48e081c620b358451,451a0567ae7c693fb2882b37860ef20d,6a9c15755566cb2f407829fb3637de52,2020-06-11 19:51:18,106.625325,Compostable Mailers,noissue-mailer-100-300mm-420mm,1,0,New
...,...,...,...,...,...,...,...,...,...,...,...
27732,2.0,167a163973c0dc784268ce1439f44731,12a8f653a63f74268a3c91602e18a931,56defccc63de74d71ae919ab1ecae656,2020-08-28 16:08:39,170.119235,noissue Stickers,custom sticker-circle-40 x 40mm-1000,1,0,New
27733,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,8855952988a815c33d84408ee4c60adb,2020-05-08 09:46:57,159.147661,noissue Stickers,custom sticker-circle-50 x 50mm-1000,0,1,Repeat
27734,4.0,cade2aee3b1062fe9c6314856ba263e7,c0b75f59becb4bb51c2f020c20241104,848f2cb9ef28ad9b821e91599a3df37a,2020-05-08 09:46:57,340.266201,noissue Tissue,own template tissue-1000#2colour-50 x 75cm,0,1,Repeat
27735,NaN,657989c9751e4f61cbf730c67ae15d4e,84409ab5d58daa0e971150510b1c106a,aaaac45627dddcb26224f41f59da5b68,2020-05-10 21:44:36,14.546653,Sample,SAMPLEPACK,1,0,New
27736,1.0,0c620bcfc2a979fe9f22acbe0019f276,23e63ace5ccf4dd62ad7da8aab98af93,f8ca2fa0793a913cc0abb9ac6e6b53a5,2020-05-19 13:04:48,516.875366,noissue Tissue,own template tissue-2000#1colour-50 x 75cm,0,1,Repeat

In [23]:
repeat_count=sales_df_dummies.groupby(sales_df_dummies["new_or_repeat_by_order"]=="Repeat").sum()
repeat_count

,skus_count,sales,cust_type_New,cust_type_Repeat
new_or_repeat_by_order,,,,
False,30837.0,3.526498e+06,19005.0,0.0
True,14405.0,2.640192e+06,0.0,8732.0

In [19]:
#export to a clean csv
sales_df_dummies.to_csv("sales_data_clean.csv")